# Generated by Django 5.0.4 on 2024-04-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0006_alter_avaliacao_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='resenha',
            name='Media_avaliacoes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
