# Generated by Django 5.0.4 on 2024-04-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0007_resenha_media_avaliacoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resenha',
            old_name='Media_avaliacoes',
            new_name='media_avaliacoes',
        ),
        migrations.AddField(
            model_name='resenha',
            name='num_resenhas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.IntegerField(),
        ),
    ]
