# Generated by Django 5.0.4 on 2024-04-20 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0008_rename_media_avaliacoes_resenha_media_avaliacoes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resenha',
            old_name='num_resenhas',
            new_name='num_avaliacoes_resenhas',
        ),
    ]
