# Generated by Django 5.0.4 on 2024-04-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0009_rename_num_resenhas_resenha_num_avaliacoes_resenhas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
