# Generated by Django 5.0.4 on 2024-04-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0010_alter_livro_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=9),
        ),
    ]
