# Generated by Django 5.0.4 on 2024-04-19 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_rename_title_livro_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='title',
            new_name='Title',
        ),
    ]
