# Generated by Django 5.0.4 on 2024-04-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_rename_title_livro_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='authors',
            field=models.CharField(default='Desconhecido', max_length=100),
            preserve_default=False,
        ),
    ]
