# Generated by Django 5.0.3 on 2024-04-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_livro_resenha_avaliação'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resenha',
            old_name='licro_id',
            new_name='livro_id',
        ),
        migrations.AlterField(
            model_name='resenha',
            name='data_publicacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
