# Generated by Django 5.0.4 on 2024-04-10 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_create_users_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
