# Generated by Django 5.0.3 on 2024-04-07 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Resenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(max_length=500)),
                ('data_publicacao', models.DateField()),
                ('licro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.livro')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliação',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('comentario', models.CharField(max_length=150)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.usuario')),
                ('resenha_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.resenha')),
            ],
        ),
    ]
