# Generated by Django 5.0.3 on 2024-04-08 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_licro_id_resenha_livro_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avaliação',
            new_name='Avaliacao',
        ),
    ]
